### PR TITLE
React capstone project - Metrics webapp

### PR DESCRIPTION
**Pull request by jerryowusu**
## Description

This is a web application for a project that uses the real COVID-19 data from Narrativa API. The data for this website is fetched from https://disease.sh/v3/covid-19/countries

### General requirements

- [x] There are **no linter errors**.
- [x] Followed the **GitFlow**.
- [x] The documentation is **professional**.

### HTML/CSS requirements

- [x] Followed best practices for JavaScript

### Project requirements

- [x] Select the API you are going to use and build files structure
- [x] Prepare routes and navigation in your app.
- [x] Make sure that a user can display a list of items and filter them. Data should come from the API.
- [x] Style your components to match the design provided.
- [x] Deploy the project and test for final details.
- [x] Record a video for your project.
- [x] Create a good README and PR description.

---
Thank you for taking the time to review this pull request.

### CODE REVIEW

**Review by Mihndim2020 — CHANGES_REQUESTED** [review]
### Hi @jerryowusu, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages,
:heavy_check_mark: Descriptive `PR` summary,
:heavy_check_mark: Descriptive  Readme file,
:heavy_check_mark: Your project is running as expected, and free of `Linter errors`.

There are some issues that you still need to work on to get this project approved, but you are almost there!
ALMOST-MINION

# Status: Requires Changes ♻️
_Check the comments below and under the review._

- [ ] Great job with the video presentation, we are just missing a bit of information, as it is a [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md)(***third point under Project Documentation section***) for this project, it will be nice to highlight  a piece of the code that you find interesting or are proud of making.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
@Mihndim2020 Thanks for the feedback,  but I believe I did mention that in the video from 2:56 to 3:20. I would be very grateful if you could check and revert back to me. Thanks again.

**Comment by omar-labana** [comment]
# **Approved ✔️**

Hi @jerryowusu,

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jerryowusu** [comment]
Thank you @omar-labana

**Pull request merged**
